CC = gcc 
CFLAGS = $(shell pkg-config --cflags libxmaplugin) 
CFLAGS += -fPIC -Wall -Wextra -O1 -g 
LDFLAGS = -shared 
RM = rm -f
TARGET_LIB = libxmacopyfilter.so

SRCS = xlnx_copyfilter.c
OBJS = $(SRCS:.c=.o)

.PHONY: all
all: ${TARGET_LIB}

$(TARGET_LIB): $(OBJS)
	$(CC) ${LDFLAGS} -o $@ $^

$(SRCS:.c=.d):%.d:%.c
	$(CC) $(CFLAGS) -MM $< >$@

include $(SRCS:.c=.d)

.PHONY: clean
clean:
	-${RM} ${TARGET_LIB} ${OBJS} $(SRCS:.c=.d)
